commit successful

diff --git a/s3/bash-scripts/create-bucket b/s3/bash-scripts/create-bucket
--- a/s3/bash-scripts/create-bucket
+++ b/s3/bash-scripts/create-bucket
@@ -1,1 +1,8 @@
 #!/usr/bin/env bash
+
+if [ -z "$1" ]; then
+  echo "Error: No input variable provided."
+  exit 1
+fi
+
+aws s3api create-bucket --bucket $1
